print("==============================")
print("   FICHA DE PERSONAJE (v1.0)")
print("==============================")
print("NOMBRE: Aelan Valdorien")
print("CLASE: Mago")
print("NIVEL: 0 (Aprendiz de Python)")
print("------------------------------")
print("¡Que comience la leyenda!")
print("==============================")
